services:
  - type: web
    name: admi-client
    runtime: static
    buildCommand: npm run build
    staticPublishPath: ./build
    autoDeploy: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
